[package]
name = "tiny-wm"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
bitflags = "2.2.1"
smithay = { version = "0.7.0", features = [
		"backend_winit",
    "wayland_frontend",
    "desktop",
] }
